version: "3.7"

services:
  backend:
    build: './backend'
    restart: always
    volumes: 
      - ./backend/:/home/app
    ports:
      - '8000:8000'

  
  nginx:
    build: './nginx'
    restart: always
    ports: 
      - '80:80'

    volumes:
     - ./frontend/yarmarkaStatistics/dist:/home/app/frontend

    depends_on:
      - backend